[package]
name = "symfritz-cli"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "symfritz"
path = "src/main.rs"

[dependencies]
clap.workspace = true
clap_complete.workspace = true
ctrlc.workspace = true
getrandom.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
rustls.workspace = true
symfritz-aha = { path = "../symfritz-aha", version = "=0.0.0" }
symfritz-core.workspace = true
symfritz-mcp = { path = "../symfritz-mcp", version = "=0.0.0" }
symfritz-tr064 = { path = "../symfritz-tr064", version = "=0.0.0" }
url.workspace = true

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true
