package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateCLIDocs(t *testing.T) {
	tmpDir := t.TempDir()
	targetPath := filepath.Join(tmpDir, "cli.md")

	root := newRootCmd()
	if err := generateCLIDocs(root, targetPath); err != nil {
		t.Fatalf("generateCLIDocs failed: %v", err)
	}

	contentBytes, err := os.ReadFile(targetPath)
	if err != nil {
		t.Fatalf("failed to read generated docs: %v", err)
	}
	content := string(contentBytes)

	// Assert do-not-edit banner
	if !strings.Contains(content, "<!-- Code generated by 'make docs' (cmd/gen-docs). DO NOT EDIT. -->") {
		t.Error("missing do-not-edit banner in generated docs")
	}

	if strings.Contains(content, "###### Auto generated by spf13/cobra on ") {
		t.Error("generated docs must not contain a volatile generation date")
	}

	// Assert documented subcommands previously missing or unindexed
	expectedSubcmds := []string{
		"symfritz home temp",
		"symfritz diagnose router",
		"symfritz auth trust",
		"symfritz status",
		"symfritz detect",
	}

	for _, cmdName := range expectedSubcmds {
		if !strings.Contains(content, cmdName) {
			t.Errorf("expected generated docs to contain %q", cmdName)
		}
	}
}
