package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

func newGenDocsCmd(root *cobra.Command) *cobra.Command {
	return &cobra.Command{
		Use:    "__gen-docs",
		Hidden: true,
		RunE: func(cmd *cobra.Command, _ []string) error {
			return generateCLIDocs(root, "docs/cli.md")
		},
	}
}

func generateCLIDocs(root *cobra.Command, targetPath string) error {
	var buf bytes.Buffer
	buf.WriteString("<!-- Code generated by 'make docs' (cmd/gen-docs). DO NOT EDIT. -->\n\n")
	buf.WriteString("# symfritz CLI Reference\n\n")
	buf.WriteString("`symfritz` is a CLI to administer, analyse, and control an AVM FRITZ!Box.\n\n")
	buf.WriteString("To regenerate this documentation: `make docs`\n\n")
	buf.WriteString("## Command List\n\n")

	cmds := collectCommands(root)

	for _, c := range cmds {
		cmdPath := c.CommandPath()
		anchor := commandAnchor(cmdPath)
		buf.WriteString(fmt.Sprintf("- [%s](#%s) — %s\n", cmdPath, anchor, c.Short))
	}
	buf.WriteString("\n---\n\n")

	emptyLinkHandler := func(name string) string {
		clean := strings.TrimSuffix(name, ".md")
		return "#" + commandAnchor(clean)
	}

	for _, c := range cmds {
		var cmdBuf bytes.Buffer
		if err := doc.GenMarkdownCustom(c, &cmdBuf, emptyLinkHandler); err != nil {
			return fmt.Errorf("generating docs for %s: %w", c.CommandPath(), err)
		}
		buf.Write(cmdBuf.Bytes())
		buf.WriteString("\n---\n\n")
	}

	dir := filepath.Dir(targetPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating docs dir: %w", err)
	}

	return os.WriteFile(targetPath, buf.Bytes(), 0644)
}

func collectCommands(cmd *cobra.Command) []*cobra.Command {
	var list []*cobra.Command
	if !cmd.Hidden {
		list = append(list, cmd)
	}
	subCmds := cmd.Commands()
	sort.Slice(subCmds, func(i, j int) bool {
		return subCmds[i].CommandPath() < subCmds[j].CommandPath()
	})
	for _, sub := range subCmds {
		if sub.Hidden {
			continue
		}
		list = append(list, collectCommands(sub)...)
	}
	return deduplicateCommands(list)
}

func deduplicateCommands(cmds []*cobra.Command) []*cobra.Command {
	seen := make(map[string]bool)
	var res []*cobra.Command
	for _, c := range cmds {
		path := c.CommandPath()
		if !seen[path] {
			seen[path] = true
			res = append(res, c)
		}
	}
	return res
}

func commandAnchor(cmdPath string) string {
	var res []rune
	for _, r := range cmdPath {
		if r == ' ' || r == ':' {
			res = append(res, '-')
		} else if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '-' {
			res = append(res, r)
		} else if r >= 'A' && r <= 'Z' {
			res = append(res, r+'a'-'A')
		}
	}
	return string(res)
}
