[package]
name = "symfritz-core"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
hex.workspace = true
md-5.workspace = true
pbkdf2.workspace = true
sha2.workspace = true

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true
